export const PERMISSIONS = {
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_SYSTEM_LOGS: 'VIEW_SYSTEM_LOGS',

  // Academic Registry
  VIEW_STUDENTS: 'VIEW_STUDENTS',
  MANAGE_ACADEMICS: 'MANAGE_ACADEMICS',

  // Finance
  MANAGE_FINANCE: 'MANAGE_FINANCE',

  // Examinations
  MANAGE_EXAMS: 'MANAGE_EXAMS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
