/**
 * Permission slugs — mirror of backend `App\Constants\Permissions`.
 *
 * Every slug here MUST exist in the backend Permissions.php class and be
 * seeded in the `permissions` table via migration. Adding a new one?
 * Add it on the backend first, then expose it here.
 */
export const PERMISSIONS = {
  // Administration
  MANAGE_ROLES:          'MANAGE_ROLES',
  MANAGE_PERMISSIONS:    'MANAGE_PERMISSIONS',
  MANAGE_USERS:          'MANAGE_USERS',
  VIEW_SYSTEM_LOGS:      'VIEW_SYSTEM_LOGS',

  // System Settings
  MANAGE_ACADEMIC_YEARS: 'MANAGE_ACADEMIC_YEARS',
  MANAGE_ACADEMIC_TERMS: 'MANAGE_ACADEMIC_TERMS',
  VIEW_SYSTEM_BASICS:    'VIEW_SYSTEM_BASICS',
  VIEW_SETTINGS:         'VIEW_SETTINGS',
  MANAGE_SETTINGS:       'MANAGE_SETTINGS',

  // Academic Registry
  VIEW_STUDENTS:      'VIEW_STUDENTS',
  MANAGE_STUDENTS:    'MANAGE_STUDENTS',
  MANAGE_ACADEMICS:   'MANAGE_ACADEMICS',
  MANAGE_DEGREES:     'MANAGE_DEGREES',
  MANAGE_FACILITIES:  'MANAGE_FACILITIES',
  MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS',
  MANAGE_OPTIONS:     'MANAGE_OPTIONS',
  MANAGE_LEVELS:      'MANAGE_LEVELS',
  MANAGE_MODULES:     'MANAGE_MODULES',
  MANAGE_SCHOOLS:     'MANAGE_SCHOOLS',
  MANAGE_CAMPUSES:    'MANAGE_CAMPUSES',
  VIEW_TIMETABLE:     'VIEW_TIMETABLE',
  MANAGE_TIMETABLE:   'MANAGE_TIMETABLE',

  // Modules Management
  MANAGE_MODULE_SCHEDULES:     'MANAGE_MODULE_SCHEDULES',
  MANAGE_MODULE_ASSIGNMENTS:   'MANAGE_MODULE_ASSIGNMENTS',
  MANAGE_MODULE_REGISTRATIONS: 'MANAGE_MODULE_REGISTRATIONS',
  VIEW_MY_MODULES:             'VIEW_MY_MODULES',
  VIEW_MODULE_MARKS:           'VIEW_MODULE_MARKS',
  RECORD_MODULE_MARKS:         'RECORD_MODULE_MARKS',
  MANAGE_MODULE_MARKS:         'MANAGE_MODULE_MARKS',

  // HR Management
  VIEW_HR_EMPLOYEES:   'VIEW_HR_EMPLOYEES',
  MANAGE_HR_EMPLOYEES: 'MANAGE_HR_EMPLOYEES',
  MANAGE_LEAVE_TYPES:  'MANAGE_LEAVE_TYPES',
  VIEW_LEAVE_REQUESTS:    'VIEW_LEAVE_REQUESTS',
  MANAGE_LEAVE_REQUESTS:  'MANAGE_LEAVE_REQUESTS',
  VIEW_PAYROLL:        'VIEW_PAYROLL',
  MANAGE_PAYROLL:      'MANAGE_PAYROLL',

  // Finance
  VIEW_FINANCE:   'VIEW_FINANCE',
  MANAGE_FINANCE: 'MANAGE_FINANCE',
  VIEW_FINANCE_OVERVIEW:        'VIEW_FINANCE_OVERVIEW',
  VIEW_FINANCE_BILLING:         'VIEW_FINANCE_BILLING',
  VIEW_FINANCE_APPROVALS:       'VIEW_FINANCE_APPROVALS',
  VIEW_FINANCE_STRUCTURES:      'VIEW_FINANCE_STRUCTURES',
  VIEW_FINANCE_BURSARIES:       'VIEW_FINANCE_BURSARIES',
  VIEW_FINANCE_SPONSORS:        'VIEW_FINANCE_SPONSORS',
  VIEW_FINANCE_EXPENSES:        'VIEW_FINANCE_EXPENSES',
  VIEW_FINANCE_REFUNDS:         'VIEW_FINANCE_REFUNDS',
  VIEW_FINANCE_BALANCE:         'VIEW_FINANCE_BALANCE',
  VIEW_FINANCE_CLEARANCE:       'VIEW_FINANCE_CLEARANCE',
  VIEW_FINANCE_REPORTS:         'VIEW_FINANCE_REPORTS',
  VIEW_MOBILE_PAYMENTS:         'VIEW_MOBILE_PAYMENTS',
  VIEW_ONLINE_PAYMENTS_HISTORY: 'VIEW_ONLINE_PAYMENTS_HISTORY',
  MY_INVOICE:                   'MY_INVOICE',

  // Admissions
  MANAGE_ADMISSION_REQUIREMENTS: 'MANAGE_ADMISSION_REQUIREMENTS',
  MANAGE_STUDENT_APPLICATIONS:   'MANAGE_STUDENT_APPLICATIONS',
  VERIFY_DOCUMENTS:              'VERIFY_DOCUMENTS',
  MANAGE_ADMISSIONS:             'MANAGE_ADMISSIONS',
  VIEW_MERIT_LIST:               'VIEW_MERIT_LIST',
  MANAGE_MERIT_LIST:             'MANAGE_MERIT_LIST',

  // Examinations
  VIEW_EXAMS:   'VIEW_EXAMS',
  MANAGE_EXAMS: 'MANAGE_EXAMS',

  // Attendance
  VIEW_ATTENDANCE:   'VIEW_ATTENDANCE',
  RECORD_ATTENDANCE: 'RECORD_ATTENDANCE',
  MANAGE_ATTENDANCE: 'MANAGE_ATTENDANCE',

  // Student Clearance
  VIEW_CLEARANCE:   'VIEW_CLEARANCE',
  MANAGE_CLEARANCE: 'MANAGE_CLEARANCE',

  // External portals (assigned to `applicant` / `student` roles via DB seed)
  ACCESS_APPLICANT_PORTAL: 'ACCESS_APPLICANT_PORTAL',
  ACCESS_STUDENT_PORTAL:   'ACCESS_STUDENT_PORTAL',

  // Applicant self-service
  MANAGE_OWN_PROFILE: 'MANAGE_OWN_PROFILE',

  // Document Generation
  GENERATE_DOCUMENTS: 'GENERATE_DOCUMENTS',

  // Messaging (seeded in migration 036)
  SEND_MESSAGES:      'SEND_MESSAGES',
  MANAGE_MESSAGES:    'MANAGE_MESSAGES',
  BROADCAST_MESSAGES: 'BROADCAST_MESSAGES',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
