export const PERMISSIONS = {
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_SYSTEM_LOGS: 'VIEW_SYSTEM_LOGS',

  // Academic Registry
  VIEW_STUDENTS: 'VIEW_STUDENTS',
  MANAGE_ACADEMICS: 'MANAGE_ACADEMICS',
  MANAGE_MODULES: 'MANAGE_MODULES',

  // Modules Management Module
  MANAGE_MODULE_SCHEDULES: 'MANAGE_MODULE_SCHEDULES',
  MANAGE_MODULE_ASSIGNMENTS: 'MANAGE_MODULE_ASSIGNMENTS',
  MANAGE_MODULE_REGISTRATIONS: 'MANAGE_MODULE_REGISTRATIONS',
  VIEW_MY_MODULES: 'VIEW_MY_MODULES',

  // Finance
  MANAGE_FINANCE: 'MANAGE_FINANCE',

  // Examinations
  MANAGE_EXAMS: 'MANAGE_EXAMS',

  // Applicant Portal
  ACCESS_APPLICANT_PORTAL: 'ACCESS_APPLICANT_PORTAL',
  
  // General Staff Access
  STAFF_ACCESS: 'STAFF_ACCESS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
