-- ──────────────────────────────────────────────────────────────────────────────
-- Migration 005_hr_module_leave_management — NEUTRALISED 2026-09-06
--
-- This migration assumed a leave schema that never became real:
--   * leave_balances with (user_id, fiscal_year, total_allocated, available) —
--     the live table (from 2026_09_05_001, which runs after this) is the
--     simpler (employee_id, year, total_days, used_days) shape.
--   * leave_types.slug / max_days_per_year — the live table has
--     (name, description, days_allowed) and no slug.
--   * a `departments` table and users.department_id for the export view —
--     neither exists in any migration.
--   * a CONSTRAINT name (`fk_lra_request`) already taken by
--     leave_request_approvals (migration 132) → errno 121 on production.
--
-- Everything it was meant to deliver is covered elsewhere:
--   * leave_requests columns          → 2026_09_05_001 (ADD COLUMN IF NOT EXISTS)
--   * leave_balances                  → 2026_09_05_001
--   * leave_types seed                → already seeded; base schema + earlier migs
--   * leave_approval_stages seed      → 2026_08_17_132 / _134 (institutional chain)
--   * leave_request_attachments /
--     leave_notifications tables      → dead — no application code references them
--     (the leave module uses the generic file store and NotificationService)
--
-- Kept as a no-op so the migrate workflow stops retrying a migration that can
-- never succeed as written.
-- ──────────────────────────────────────────────────────────────────────────────

SELECT 'noop: 2026_09_04_005_hr_module_leave_management (neutralised — see header)' AS note;
