import { useEffect, useState } from 'react'
import { useQuery, useMutation } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { FileText, Banknote, Loader2, X, Plus, AlertTriangle } from 'lucide-react'
import toast from 'react-hot-toast'
import { ledgerService } from '@/services/financeService'
import { academicService } from '@/services/academicService'
import type { FeeInvoice, FeeType } from '@/types/finance'
import { FEE_TYPE_LABELS, PAYMENT_METHOD_LABELS, BANK_SUB_METHOD_LABELS, MOMO_SUB_METHOD_LABELS } from '@/types/finance'
import InvoiceStatusBadge from '@/components/finance/InvoiceStatusBadge'
import GenerateInvoicesModal from './GenerateInvoicesModal'
import RecordPaymentModal from './RecordPaymentModal'
import StudentSearchSelect from '@/components/finance/StudentSearchSelect'
import SearchableSelect from '@/components/ui/SearchableSelect'
import { useSystemStore, selectActiveYear } from '@/store/systemStore'
import { formatRWF } from '@/utils/formatCurrency'

// Fee types that can be manually created (not auto-generated by the system)
const MANUAL_FEE_TYPES: FeeType[] = ['FINE', 'ACADEMIC_DOCUMENT', 'HOSTEL', 'ADMISSION']

export default function StudentLedgerPage() {
  const activeYear = useSystemStore(selectActiveYear)

  const [studentId, setStudentId]   = useState('')
  const [studentName, setStudentName] = useState('')
  const [yearId, setYearId]         = useState<number | string>('')
  const [showGenerate, setShowGenerate] = useState(false)
  const [showNewInvoice, setShowNewInvoice] = useState(false)
  const [payingInvoice, setPayingInvoice] = useState<FeeInvoice | null>(null)
  const [viewingInvoice, setViewingInvoice] = useState<FeeInvoice | null>(null)

  useEffect(() => {
    if (activeYear?.id && !yearId) setYearId(activeYear.id)
  }, [activeYear?.id]) // eslint-disable-line

  const yearsQ = useQuery({
    queryKey: ['academic-years'],
    queryFn: () => academicService.listYears(),
  })
  const years = yearsQ.data?.data ?? []
  const yearOptions = years.map((y: any) => ({ value: y.id, label: y.label }))

  const ledgerQ = useQuery({
    queryKey: ['finance', 'ledger', studentId, yearId],
    queryFn: () => ledgerService.getStudentLedger(studentId, yearId ? { academic_year_id: Number(yearId) } : {}),
    enabled: !!studentId,
  })

  const ledger   = ledgerQ.data?.data
  const invoices = ledger?.invoices ?? []
  const payments = ledger?.payments ?? []
  const totals   = ledger?.totals

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div>
          <h2 className="text-lg font-bold text-ink-900 dark:text-white">Student Ledger</h2>
          <p className="text-[13px] text-ink-500">View and manage fees, invoices and payments per student.</p>
        </div>
        {studentId && (
          <div className="flex gap-2">
            <button className="btn-ghost btn-sm" onClick={() => setShowNewInvoice(true)}>
              <Plus className="w-3.5 h-3.5" /> New Invoice
            </button>
            <button className="btn-secondary btn-sm" onClick={() => setShowGenerate(true)}>
              <FileText className="w-3.5 h-3.5" /> Generate Invoices
            </button>
          </div>
        )}
      </div>

      {/* Search bar */}
      <div className="card p-3 flex gap-3 items-end flex-wrap">
        <div className="flex-1 min-w-[260px]">
          <label className="block text-xs text-ink-500 mb-1">Student</label>
          <StudentSearchSelect
            value={studentId}
            onChange={(regnum, name) => {
              setStudentId(regnum)
              setStudentName(name ?? '')
            }}
            placeholder="Search by name or registration number…"
          />
        </div>

        <div className="min-w-[180px]">
          <label className="block text-xs text-ink-500 mb-1">Academic Year</label>
          <SearchableSelect
            options={yearOptions}
            value={yearId}
            onChange={v => setYearId(v)}
            placeholder="All years"
            allLabel="All years"
          />
        </div>
      </div>

      {ledgerQ.isLoading && (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="w-5 h-5 animate-spin text-brand" />
        </div>
      )}

      {ledger && (
        <>
          {/* Student header */}
          {studentName && (
            <div className="card px-4 py-3 flex items-center justify-between gap-3 flex-wrap">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-full bg-brand/10 flex items-center justify-center text-brand font-bold text-sm shrink-0">
                  {studentName.charAt(0)}
                </div>
                <div>
                  <p className="font-semibold text-sm text-ink-900 dark:text-white">{studentName}</p>
                  <p className="text-xs text-ink-400 font-mono">{studentId}</p>
                </div>
              </div>
              
              {yearId && totals && (
                <div className={`px-3 py-1 rounded-full text-xs font-semibold flex items-center gap-1.5 ${
                  Number(totals.balance) <= 0 
                    ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                    : 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
                }`}>
                  {Number(totals.balance) <= 0 ? 'Cleared for Year' : 'Balance Pending'}
                </div>
              )}
            </div>
          )}

          {/* Totals */}
          {totals && yearId && (
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <SummaryCard label="Total Due"  value={totals.total_due}    color="text-ink-700" />
              <SummaryCard label="Total Paid" value={totals.total_paid}   color="text-green-600" />
              <SummaryCard label="Bursary"    value={totals.total_bursary} color="text-blue-600" />
              <SummaryCard
                label="Balance"
                value={totals.balance}
                color={Number(totals.balance) > 0 ? 'text-red-600' : 'text-green-600'}
              />
            </div>
          )}

          {/* Invoices */}
          <div className="card overflow-hidden">
            <div className="px-4 py-2.5 border-b border-ink-100 dark:border-ink-700 font-medium text-sm flex items-center justify-between bg-ink-50/50 dark:bg-ink-700/20">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-ink-400" />
                <span>Invoices</span>
                <span className="text-[10px] bg-ink-100 dark:bg-ink-700 px-1.5 py-0.5 rounded text-ink-500 font-mono">{invoices.length}</span>
              </div>
              <button 
                className="btn-ghost btn-xs text-brand flex items-center gap-1 hover:bg-brand/10"
                onClick={() => setShowNewInvoice(true)}
              >
                <Plus className="w-3 h-3" /> Record Manual Fee
              </button>
            </div>
            {invoices.length === 0 ? (
              <div className="text-center py-10 text-ink-400 text-sm">
                <FileText className="w-8 h-8 mx-auto mb-2 opacity-30" />
                <p>No invoices found for this student.</p>
                <button
                  className="btn-secondary btn-sm mt-3"
                  onClick={() => setShowGenerate(true)}
                >
                  <FileText className="w-3.5 h-3.5" /> Generate Invoices
                </button>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-ink-50 dark:bg-ink-700/50 text-ink-500 text-xs uppercase">
                    <tr>
                      <th className="px-4 py-2.5 text-left">Invoice #</th>
                      <th className="px-4 py-2.5 text-left">Type</th>
                      <th className="px-4 py-2.5 text-left">Description</th>
                      <th className="px-4 py-2.5 text-left">Due Date</th>
                      <th className="px-4 py-2.5 text-right">Amount Due</th>
                      <th className="px-4 py-2.5 text-right">Paid</th>
                      <th className="px-4 py-2.5 text-center">Status</th>
                      <th className="px-4 py-2.5" />
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-ink-100 dark:divide-ink-700">
                    {invoices.map((inv: FeeInvoice) => (
                      <tr
                        key={inv.id}
                        className="hover:bg-ink-50/50 dark:hover:bg-ink-700/30 cursor-pointer"
                        onClick={() => setViewingInvoice(inv)}
                      >
                        <td className="px-4 py-2.5 font-mono text-xs">{inv.invoice_number}</td>
                        <td className="px-4 py-2.5 text-ink-500 text-xs">{FEE_TYPE_LABELS[inv.fee_type]}</td>
                        <td className="px-4 py-2.5">{inv.description}</td>
                        <td className="px-4 py-2.5 text-ink-500 text-xs">{inv.due_date ?? '—'}</td>
                        <td className="px-4 py-2.5 text-right font-mono">{formatRWF(inv.amount_due)}</td>
                        <td className="px-4 py-2.5 text-right font-mono text-green-600">{formatRWF(inv.amount_paid)}</td>
                        <td className="px-4 py-2.5 text-center">
                          <InvoiceStatusBadge status={inv.status} />
                        </td>
                        <td className="px-4 py-2.5" onClick={e => e.stopPropagation()}>
                          {inv.status !== 'paid' && inv.status !== 'waived' && inv.fee_type !== 'BURSARY_CREDIT' && (
                            <button
                              className="btn-ghost btn-xs text-brand"
                              onClick={() => setPayingInvoice(inv)}
                            >
                              <Banknote className="w-3.5 h-3.5" /> Pay
                            </button>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Payments history */}
          {payments.length > 0 && (
            <div className="card overflow-hidden">
              <div className="px-4 py-3 border-b border-ink-100 dark:border-ink-700 font-medium text-sm flex items-center justify-between">
                <span>Payment History</span>
                <span className="text-xs text-ink-400">{payments.length} payment{payments.length !== 1 ? 's' : ''}</span>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-ink-50 dark:bg-ink-700/50 text-ink-500 text-xs uppercase">
                    <tr>
                      <th className="px-4 py-2.5 text-left">Receipt #</th>
                      <th className="px-4 py-2.5 text-left">Method</th>
                      <th className="px-4 py-2.5 text-left">Reference</th>
                      <th className="px-4 py-2.5 text-left">Date</th>
                      <th className="px-4 py-2.5 text-right">Amount</th>
                      <th className="px-4 py-2.5" />
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-ink-100 dark:divide-ink-700">
                    {payments.map((p: any) => (
                      <tr key={p.id} className="hover:bg-ink-50/50 dark:hover:bg-ink-700/30">
                        <td className="px-4 py-2.5 font-mono text-xs">{p.receipt_number}</td>
                        <td className="px-4 py-2.5 text-ink-500">
                          {p.payment_sub_method 
                            ? ((BANK_SUB_METHOD_LABELS as any)[p.payment_sub_method] || (MOMO_SUB_METHOD_LABELS as any)[p.payment_sub_method] || p.payment_sub_method.replace(/_/g, ' '))
                            : ((PAYMENT_METHOD_LABELS as any)[p.payment_method] ?? p.payment_method.replace(/_/g, ' '))}
                        </td>
                        <td className="px-4 py-2.5 text-ink-500 text-xs">{p.reference_number ?? '—'}</td>
                        <td className="px-4 py-2.5 text-ink-500 text-xs">{p.paid_at ? new Date(p.paid_at).toLocaleDateString() : '—'}</td>
                        <td className="px-4 py-2.5 text-right font-mono font-semibold text-green-600">{formatRWF(p.amount)}</td>
                        <td className="px-4 py-2.5">
                          <Link to={`/finance/receipt/${p.id}`} target="_blank" rel="noreferrer" className="btn-ghost btn-xs text-brand">
                            <FileText className="w-3.5 h-3.5" /> Receipt
                          </Link>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}

      {!studentId && (
        <div className="card p-12 text-center text-ink-400">
          <FileText className="w-10 h-10 mx-auto mb-3 opacity-30" />
          <p className="text-sm">Search for a student above to view their ledger.</p>
        </div>
      )}

      {showGenerate && studentId && (
        <GenerateInvoicesModal
          studentId={studentId}
          years={years}
          defaultYearId={yearId ? Number(yearId) : activeYear?.id}
          onClose={() => setShowGenerate(false)}
          onDone={() => { setShowGenerate(false); ledgerQ.refetch() }}
        />
      )}

      {showNewInvoice && studentId && (
        <ManualInvoiceModal
          studentId={studentId}
          yearId={yearId ? Number(yearId) : activeYear?.id ?? 0}
          onClose={() => setShowNewInvoice(false)}
          onDone={() => { setShowNewInvoice(false); ledgerQ.refetch() }}
        />
      )}

      {payingInvoice && (
        <RecordPaymentModal
          invoice={payingInvoice}
          onClose={() => setPayingInvoice(null)}
          onDone={() => { setPayingInvoice(null); ledgerQ.refetch() }}
        />
      )}

      {viewingInvoice && (
        <InvoiceDetailModal
          invoice={viewingInvoice}
          onClose={() => setViewingInvoice(null)}
          onPay={() => { setPayingInvoice(viewingInvoice); setViewingInvoice(null) }}
          onWaived={() => { setViewingInvoice(null); ledgerQ.refetch() }}
        />
      )}
    </div>
  )
}

// ─── Invoice Detail Modal ─────────────────────────────────────────────────────

function InvoiceDetailModal({ invoice: inv, onClose, onPay, onWaived }: {
  invoice:  FeeInvoice
  onClose:  () => void
  onPay:    () => void
  onWaived: () => void
}) {
  const balance = Number(inv.amount_due) - Number(inv.amount_paid) - Number((inv as any).bursary_applied ?? 0)
  const canPay   = inv.status !== 'paid' && inv.status !== 'waived' && inv.fee_type !== 'BURSARY_CREDIT'
  const canWaive = ['unpaid', 'partial', 'overdue'].includes(inv.status) && inv.fee_type !== 'BURSARY_CREDIT'

  const [confirming, setConfirming] = useState(false)

  const waiveMutation = useMutation({
    mutationFn: () => ledgerService.updateInvoice(inv.id, { status: 'waived' }),
    onSuccess: () => {
      toast.success('Invoice waived successfully')
      onWaived()
    },
    onError: (e: any) => toast.error(e?.response?.data?.message ?? 'Waive failed'),
  })

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50">
      <div className="flex min-h-full items-center justify-center p-4">
        <div className="bg-white dark:bg-ink-800 rounded-xl shadow-xl w-full max-w-sm p-6 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-semibold">Invoice Details</h3>
            <button className="btn-ghost btn-xs" onClick={onClose}><X className="w-4 h-4" /></button>
          </div>

          <div className="space-y-2 text-sm">
            <Row label="Invoice #"     value={<span className="font-mono">{inv.invoice_number}</span>} />
            <Row label="Fee Type"      value={FEE_TYPE_LABELS[inv.fee_type] ?? inv.fee_type} />
            <Row label="Description"   value={inv.description} />
            <Row label="Academic Year" value={(inv as any).academic_year_label ?? '—'} />
            <Row label="Due Date"      value={inv.due_date ?? '—'} />
            <Row label="Status"        value={<InvoiceStatusBadge status={inv.status} />} />
          </div>

          <div className="bg-ink-50 dark:bg-ink-700/40 rounded-lg p-3 space-y-1.5 text-sm">
            <div className="flex justify-between">
              <span className="text-ink-500">Amount Due</span>
              <span className="font-mono font-semibold">{formatRWF(inv.amount_due)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-ink-500">Paid</span>
              <span className="font-mono text-green-600">{formatRWF(inv.amount_paid)}</span>
            </div>
            {Number((inv as any).bursary_applied ?? 0) > 0 && (
              <div className="flex justify-between">
                <span className="text-ink-500">Bursary Applied</span>
                <span className="font-mono text-blue-600">{formatRWF((inv as any).bursary_applied)}</span>
              </div>
            )}
            <div className="flex justify-between border-t border-ink-200 dark:border-ink-600 pt-1.5 mt-1.5">
              <span className="font-medium">Balance</span>
              <span className={`font-mono font-bold ${balance > 0 ? 'text-red-600' : 'text-green-600'}`}>
                {formatRWF(balance)}
              </span>
            </div>
          </div>

          {/* Waive confirmation */}
          {confirming && (
            <div className="bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800 rounded-lg p-3 space-y-2">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-orange-500 shrink-0 mt-0.5" />
                <p className="text-sm text-orange-700 dark:text-orange-400">
                  This will mark the invoice as <strong>waived</strong> and no payment will be required. This action cannot be undone.
                </p>
              </div>
              <div className="flex gap-2 justify-end">
                <button className="btn-ghost btn-xs" onClick={() => setConfirming(false)}>Cancel</button>
                <button
                  className="btn-xs bg-orange-500 hover:bg-orange-600 text-white rounded px-3"
                  onClick={() => waiveMutation.mutate()}
                  disabled={waiveMutation.isPending}
                >
                  {waiveMutation.isPending && <Loader2 className="w-3 h-3 animate-spin" />}
                  Confirm Waive
                </button>
              </div>
            </div>
          )}

          <div className="flex gap-2 justify-between pt-1">
            <div>
              {canWaive && !confirming && (
                <button
                  className="btn-ghost btn-sm text-orange-600 dark:text-orange-400"
                  onClick={() => setConfirming(true)}
                >
                  <AlertTriangle className="w-3.5 h-3.5" /> Waive
                </button>
              )}
            </div>
            <div className="flex gap-2">
              <button className="btn-ghost btn-sm" onClick={onClose}>Close</button>
              {canPay && (
                <button className="btn-primary btn-sm" onClick={onPay}>
                  <Banknote className="w-3.5 h-3.5" /> Record Payment
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Manual Invoice Modal ─────────────────────────────────────────────────────

function ManualInvoiceModal({ studentId, yearId, onClose, onDone }: {
  studentId: string
  yearId:    number
  onClose:   () => void
  onDone:    () => void
}) {
  const feeTypeOptions = MANUAL_FEE_TYPES.map(t => ({ value: t, label: FEE_TYPE_LABELS[t] }))

  const [form, setForm] = useState({
    fee_type:    'FINE' as FeeType,
    description: '',
    amount_due:  0,
    due_date:    '',
  })

  const set = (k: keyof typeof form, v: any) => setForm(f => ({ ...f, [k]: v }))

  const mutation = useMutation({
    mutationFn: () =>
      ledgerService.createInvoice({
        student_id:       studentId,
        academic_year_id: yearId,
        fee_type:         form.fee_type,
        description:      form.description,
        amount_due:       form.amount_due,
        due_date:         form.due_date || null,
      }),
    onSuccess: () => {
      toast.success('Invoice created successfully')
      onDone()
    },
    onError: (e: any) => toast.error(e?.response?.data?.message ?? 'Create failed'),
  })

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50">
      <div className="flex min-h-full items-center justify-center p-4">
        <div className="bg-white dark:bg-ink-800 rounded-xl shadow-xl w-full max-w-sm p-6 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-semibold">New Invoice</h3>
            <button className="btn-ghost btn-xs" onClick={onClose}><X className="w-4 h-4" /></button>
          </div>

          <div className="space-y-3 text-sm">
            <div>
              <label className="block text-xs text-ink-500 mb-1">Fee Type *</label>
              <SearchableSelect
                options={feeTypeOptions}
                value={form.fee_type}
                onChange={v => set('fee_type', v as FeeType)}
                placeholder="Select fee type…"
              />
            </div>

            <div>
              <label className="block text-xs text-ink-500 mb-1">Description *</label>
              <input
                className="input input-sm w-full"
                value={form.description}
                onChange={e => set('description', e.target.value)}
                placeholder="e.g. Library fine – overdue books"
              />
            </div>

            <div>
              <label className="block text-xs text-ink-500 mb-1">Amount (RWF) *</label>
              <input
                type="number"
                className="input input-sm w-full"
                value={form.amount_due}
                min={1}
                onChange={e => set('amount_due', Number(e.target.value))}
              />
            </div>

            <div>
              <label className="block text-xs text-ink-500 mb-1">Due Date (optional)</label>
              <input
                type="date"
                className="input input-sm w-full"
                value={form.due_date}
                onChange={e => set('due_date', e.target.value)}
              />
            </div>
          </div>

          <div className="flex gap-2 justify-end pt-2">
            <button className="btn-ghost btn-sm" onClick={onClose}>Cancel</button>
            <button
              className="btn-primary btn-sm"
              onClick={() => mutation.mutate()}
              disabled={mutation.isPending || !form.description || form.amount_due <= 0}
            >
              {mutation.isPending && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
              Create Invoice
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Helper sub-components ────────────────────────────────────────────────────

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex justify-between gap-4">
      <span className="text-ink-500 shrink-0">{label}</span>
      <span className="text-right font-medium text-ink-800 dark:text-ink-100">{value}</span>
    </div>
  )
}

function SummaryCard({ label, value, color }: { label: string; value: number | null; color: string }) {
  return (
    <div className="card p-4">
      <p className="text-xs text-ink-500 mb-1">{label}</p>
      <p className={`text-xl font-bold ${color}`}>
        {formatRWF(value ?? 0)}
      </p>
    </div>
  )
}
