import { useEffect, useMemo, useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Link, useParams, useNavigate } from "react-router-dom";
import {
  FileText,
  Banknote,
  Loader2,
  X,
  Plus,
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Info,
} from "lucide-react";
import toast from "react-hot-toast";
import { ledgerService, feeStructureService } from "@/services/financeService";
import { academicService } from "@/services/academicService";
import type { FeeInvoice, FeeType, FeeStructure } from "@/types/finance";
import {
  FEE_TYPE_LABELS,
  PAYMENT_METHOD_LABELS,
  BANK_SUB_METHOD_LABELS,
  MOMO_SUB_METHOD_LABELS,
} from "@/types/finance";
import InvoiceStatusBadge from "@/components/finance/InvoiceStatusBadge";
import GenerateInvoicesModal from "./GenerateInvoicesModal";
import RecordPaymentModal from "./RecordPaymentModal";
import StudentSearchSelect from "@/components/finance/StudentSearchSelect";
import SearchableSelect from "@/components/ui/SearchableSelect";
import { useSystemStore } from "@/store/systemStore";
import { formatRWF } from "@/utils/formatCurrency";
import ModalPortal from "@/components/ui/ModalPortal";

// Fee types that can be manually created (not auto-generated by the system)
const MANUAL_FEE_TYPES: FeeType[] = [
  "FINE",
  "ACADEMIC_DOCUMENT",
  "HOSTEL",
  "ADMISSION",
  "REPEAT_MODULE",
  "ARREARS",
];

export default function StudentLedgerPage() {
  const params = useParams();
  const urlId = params["*"];

  const navigate = useNavigate();
  const basics = useSystemStore((s) => s.basics);
  const selectedYearLabel = useSystemStore((s) => s.selectedYearLabel);

  const resolveYearId = (label: string, b: typeof basics): number | string => {
    if (label) {
      const found = b?.years?.find((y) => y.label === label);
      if (found) return found.id;
    }
    return (b?.active_year as any)?.id ?? "";
  };

  const [studentId, setStudentId] = useState(urlId ?? "");
  const [studentName, setStudentName] = useState("");
  const [yearId, setYearId] = useState<number | string>(() =>
    resolveYearId(selectedYearLabel, basics),
  );
  const [showGenerate, setShowGenerate] = useState(false);
  const [showNewInvoice, setShowNewInvoice] = useState(false);
  const [payingInvoice, setPayingInvoice] = useState<FeeInvoice | null>(null);
  const [viewingInvoice, setViewingInvoice] = useState<FeeInvoice | null>(null);

  // Sync local yearId when the global selector changes
  useEffect(() => {
    setYearId(resolveYearId(selectedYearLabel, basics));
  }, [selectedYearLabel, basics?.years]);

  useEffect(() => {
    if (urlId) setStudentId(urlId);
  }, [urlId]);

  const yearsQ = useQuery({
    queryKey: ["academic-years"],
    queryFn: () => academicService.listYears(),
  });
  const years = yearsQ.data?.data ?? [];
  const yearOptions = years.map((y: any) => ({ value: y.id, label: y.label }));

  const ledgerQ = useQuery({
    queryKey: ["finance", "ledger", studentId, yearId],
    queryFn: () =>
      ledgerService.getStudentLedger(
        studentId,
        yearId ? { academic_year_id: Number(yearId) } : {},
      ),
    enabled: !!studentId,
  });

  const ledger = ledgerQ.data?.data;
  const invoices = ledger?.invoices ?? [];
  // Only expose confirmed payments — pending/rejected are internal officer state
  const payments = (ledger?.payments ?? []).filter(
    (p: any) => p.status === "confirmed",
  );
  const totals = ledger?.totals;

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="w-8 h-8 rounded-full border border-ink-200 dark:border-ink-700 flex items-center justify-center text-ink-400 hover:text-brand hover:border-brand transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <h2 className="text-lg font-bold text-ink-900 dark:text-white">
              Student Ledger
            </h2>
            <p className="text-[13px] text-ink-500">
              View and manage fees, invoices and payments per student.
            </p>
          </div>
        </div>
        {studentId && (
          <div className="flex gap-2">
            <button
              className="btn-ghost btn-sm"
              onClick={() => setShowNewInvoice(true)}
            >
              <Plus className="w-3.5 h-3.5" /> New Invoice
            </button>
          </div>
        )}
      </div>

      {/* Search bar */}
      <div className="card p-3 flex gap-3 items-end flex-wrap">
        <div className="flex-1 min-w-[260px]">
          <label className="block text-xs text-ink-500 mb-1">Student</label>
          <StudentSearchSelect
            value={studentId}
            onChange={(regnum, name) => {
              setStudentId(regnum);
              setStudentName(name ?? "");
            }}
            placeholder="Search by name or registration number…"
          />
        </div>

        <div className="min-w-[180px]">
          <label className="block text-xs text-ink-500 mb-1">
            Academic Year
          </label>
          <SearchableSelect
            options={yearOptions}
            value={yearId}
            onChange={(v) => setYearId(v)}
            placeholder="All years"
            allLabel="All years"
          />
        </div>
      </div>

      {ledgerQ.isLoading && (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="w-5 h-5 animate-spin text-brand" />
        </div>
      )}

      {ledger && (
        <>
          {/* Student header */}
          {studentName && (
            <div className="card px-4 py-3 flex items-center justify-between gap-3 flex-wrap">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-full bg-brand/10 flex items-center justify-center text-brand font-bold text-sm shrink-0">
                  {studentName.charAt(0)}
                </div>
                <div>
                  <p className="font-semibold text-sm text-ink-900 dark:text-white">
                    {studentName}
                  </p>
                  <p className="text-xs text-ink-400 font-mono">{studentId}</p>
                </div>
              </div>

              {yearId && totals && (
                <div
                  className={`px-3 py-1 rounded-full text-xs font-semibold flex items-center gap-1.5 ${
                    Number(totals.balance) <= 0
                      ? "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400"
                      : "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400"
                  }`}
                >
                  {Number(totals.balance) <= 0
                    ? "Cleared for Year"
                    : "Balance Pending"}
                </div>
              )}
            </div>
          )}

          {/* Totals */}
          {totals && yearId && (
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <SummaryCard
                label="Total Due"
                value={totals.total_due}
                color="text-ink-700"
              />
              <SummaryCard
                label="Total Paid"
                value={totals.total_paid}
                color="text-green-600"
              />
              <SummaryCard
                label="Bursary"
                value={totals.total_bursary}
                color="text-blue-600"
              />
              <SummaryCard
                label="Balance"
                value={totals.balance}
                color={
                  Number(totals.balance) > 0 ? "text-red-600" : "text-green-600"
                }
              />
            </div>
          )}

          {/* Invoices */}
          <div className="card overflow-hidden">
            <div className="px-4 py-2.5 border-b border-ink-100 dark:border-ink-700 font-medium text-sm flex items-center gap-2 bg-ink-50/50 dark:bg-ink-700/20">
              <FileText className="w-4 h-4 text-ink-400" />
              <span>Invoices</span>
              <span className="text-[10px] bg-ink-100 dark:bg-ink-700 px-1.5 py-0.5 rounded text-ink-500 font-mono">
                {invoices.length}
              </span>
            </div>
            {invoices.length === 0 ? (
              <div className="text-center py-10 text-ink-400 text-sm">
                <FileText className="w-8 h-8 mx-auto mb-2 opacity-30" />
                <p>No invoices found for this student.</p>
                <button
                  className="btn-secondary btn-sm mt-3"
                  onClick={() => setShowNewInvoice(true)}
                >
                  <FileText className="w-3.5 h-3.5" /> New Invoices
                </button>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-ink-50 dark:bg-ink-700/50 text-ink-500 text-xs uppercase">
                    <tr>
                      <th className="px-4 py-2.5 text-left">Invoice #</th>
                      <th className="px-4 py-2.5 text-left">Type</th>
                      <th className="px-4 py-2.5 text-left">Description</th>
                      <th className="px-4 py-2.5 text-left">Due Date</th>
                      <th className="px-4 py-2.5 text-right">Amount Due</th>
                      <th className="px-4 py-2.5 text-right">Paid</th>
                      <th className="px-4 py-2.5 text-center">Status</th>
                      <th className="px-4 py-2.5" />
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-ink-100 dark:divide-ink-700">
                    {invoices.map((inv: FeeInvoice) => (
                      <tr
                        key={inv.id}
                        className="hover:bg-ink-50/50 dark:hover:bg-ink-700/30 cursor-pointer"
                        onClick={() => setViewingInvoice(inv)}
                      >
                        <td className="px-4 py-2.5 font-mono text-xs">
                          {inv.invoice_number}
                        </td>
                        <td className="px-4 py-2.5 text-ink-500 text-xs">
                          {FEE_TYPE_LABELS[inv.fee_type]}
                        </td>
                        <td className="px-4 py-2.5">{inv.description}</td>
                        <td className="px-4 py-2.5 text-ink-500 text-xs">
                          {inv.due_date ?? "—"}
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono">
                          {formatRWF(inv.amount_due)}
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono text-green-600">
                          {formatRWF(inv.amount_paid)}
                        </td>
                        <td className="px-4 py-2.5 text-center">
                          <InvoiceStatusBadge status={inv.status} />
                        </td>
                        <td
                          className="px-4 py-2.5"
                          onClick={(e) => e.stopPropagation()}
                        >
                          {inv.status !== "paid" &&
                            inv.status !== "waived" &&
                            inv.fee_type !== "BURSARY_CREDIT" && (
                              <button
                                className="btn-ghost btn-xs text-brand"
                                onClick={() => setPayingInvoice(inv)}
                              >
                                <Banknote className="w-3.5 h-3.5" /> Pay
                              </button>
                            )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Payments history */}
          {payments.length > 0 && (
            <div className="card overflow-hidden">
              <div className="px-4 py-3 border-b border-ink-100 dark:border-ink-700 font-medium text-sm flex items-center justify-between">
                <span>Payment History</span>
                <span className="text-xs text-ink-400">
                  {payments.length} payment{payments.length !== 1 ? "s" : ""}
                </span>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-ink-50 dark:bg-ink-700/50 text-ink-500 text-xs uppercase">
                    <tr>
                      <th className="px-4 py-2.5 text-left">Receipt #</th>
                      <th className="px-4 py-2.5 text-left">Method</th>
                      <th className="px-4 py-2.5 text-left">Reference</th>
                      <th className="px-4 py-2.5 text-left">Date</th>
                      <th className="px-4 py-2.5 text-right">Amount</th>
                      <th className="px-4 py-2.5" />
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-ink-100 dark:divide-ink-700">
                    {payments.map((p: any) => (
                      <tr
                        key={p.id}
                        className="hover:bg-ink-50/50 dark:hover:bg-ink-700/30"
                      >
                        <td className="px-4 py-2.5 font-mono text-xs">
                          {p.receipt_number}
                        </td>
                        <td className="px-4 py-2.5 text-ink-500">
                          {p.payment_sub_method
                            ? (BANK_SUB_METHOD_LABELS as any)[
                                p.payment_sub_method
                              ] ||
                              (MOMO_SUB_METHOD_LABELS as any)[
                                p.payment_sub_method
                              ] ||
                              p.payment_sub_method.replace(/_/g, " ")
                            : ((PAYMENT_METHOD_LABELS as any)[
                                p.payment_method
                              ] ?? p.payment_method.replace(/_/g, " "))}
                        </td>
                        {/* reference_number is student-facing info (bank slip ref) — safe to show */}
                        <td className="px-4 py-2.5 text-ink-500 text-xs">
                          {p.reference_number ?? "—"}
                        </td>
                        <td className="px-4 py-2.5 text-ink-500 text-xs">
                          {p.paid_at
                            ? new Date(p.paid_at).toLocaleDateString()
                            : "—"}
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono font-semibold text-green-600">
                          {formatRWF(p.amount)}
                        </td>
                        <td className="px-4 py-2.5">
                          <Link
                            to={`/finance/receipt/${p.id}`}
                            target="_blank"
                            rel="noreferrer"
                            className="btn-ghost btn-xs text-brand"
                          >
                            <FileText className="w-3.5 h-3.5" /> Receipt
                          </Link>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}

      {!studentId && (
        <div className="card p-12 text-center text-ink-400">
          <FileText className="w-10 h-10 mx-auto mb-3 opacity-30" />
          <p className="text-sm">
            Search for a student above to view their ledger.
          </p>
        </div>
      )}

      {showGenerate && studentId && (
        <GenerateInvoicesModal
          studentId={studentId}
          years={years}
          defaultYearId={
            yearId ? Number(yearId) : (basics?.active_year as any)?.id
          }
          onClose={() => setShowGenerate(false)}
          onDone={() => {
            setShowGenerate(false);
            ledgerQ.refetch();
          }}
        />
      )}

      {showNewInvoice && studentId && (
        <ManualInvoiceModal
          studentId={studentId}
          yearId={
            yearId ? Number(yearId) : ((basics?.active_year as any)?.id ?? 0)
          }
          existingInvoices={invoices}
          onClose={() => setShowNewInvoice(false)}
          onDone={() => {
            setShowNewInvoice(false);
            ledgerQ.refetch();
          }}
        />
      )}

      {payingInvoice && (
        <RecordPaymentModal
          invoice={payingInvoice}
          onClose={() => setPayingInvoice(null)}
          onDone={() => {
            setPayingInvoice(null);
            ledgerQ.refetch();
          }}
        />
      )}

      {viewingInvoice && (
        <InvoiceDetailModal
          invoice={viewingInvoice}
          onClose={() => setViewingInvoice(null)}
          onPay={() => {
            setPayingInvoice(viewingInvoice);
            setViewingInvoice(null);
          }}
          onWaived={() => {
            setViewingInvoice(null);
            ledgerQ.refetch();
          }}
        />
      )}
    </div>
  );
}

// ─── Invoice Detail Modal ─────────────────────────────────────────────────────

function InvoiceDetailModal({
  invoice: inv,
  onClose,
  onPay,
  onWaived,
}: {
  invoice: FeeInvoice;
  onClose: () => void;
  onPay: () => void;
  onWaived: () => void;
}) {
  const balance =
    Number(inv.amount_due) -
    Number(inv.amount_paid) -
    Number((inv as any).bursary_applied ?? 0);
  const canPay =
    inv.status !== "paid" &&
    inv.status !== "waived" &&
    inv.fee_type !== "BURSARY_CREDIT";
  const canWaive =
    ["unpaid", "partial", "overdue"].includes(inv.status) &&
    inv.fee_type !== "BURSARY_CREDIT";

  const [confirming, setConfirming] = useState(false);

  const waiveMutation = useMutation({
    mutationFn: () => ledgerService.updateInvoice(inv.id, { status: "waived" }),
    onSuccess: () => {
      toast.success("Invoice waived successfully");
      onWaived();
    },
    onError: (e: any) =>
      toast.error(e?.response?.data?.message ?? "Waive failed"),
  });

  return (
    <ModalPortal>
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50">
      <div className="flex min-h-full items-center justify-center p-4">
        <div className="bg-white dark:bg-ink-800 rounded-xl shadow-xl w-full max-w-2xl p-6 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-semibold">Invoice Details</h3>
            <button className="btn-ghost btn-xs" onClick={onClose}>
              <X className="w-4 h-4" />
            </button>
          </div>

          <div className="space-y-2 text-sm">
            <Row
              label="Invoice #"
              value={<span className="font-mono">{inv.invoice_number}</span>}
            />
            <Row
              label="Fee Type"
              value={FEE_TYPE_LABELS[inv.fee_type] ?? inv.fee_type}
            />
            <Row label="Description" value={inv.description} />
            <Row
              label="Academic Year"
              value={(inv as any).academic_year_label ?? "—"}
            />
            <Row label="Due Date" value={inv.due_date ?? "—"} />
            <Row
              label="Status"
              value={<InvoiceStatusBadge status={inv.status} />}
            />
          </div>

          <div className="bg-ink-50 dark:bg-ink-700/40 rounded-lg p-3 space-y-1.5 text-sm">
            <div className="flex justify-between">
              <span className="text-ink-500">Amount Due</span>
              <span className="font-mono font-semibold">
                {formatRWF(inv.amount_due)}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-ink-500">Paid</span>
              <span className="font-mono text-green-600">
                {formatRWF(inv.amount_paid)}
              </span>
            </div>
            {Number((inv as any).bursary_applied ?? 0) > 0 && (
              <div className="flex justify-between">
                <span className="text-ink-500">Bursary Applied</span>
                <span className="font-mono text-blue-600">
                  {formatRWF((inv as any).bursary_applied)}
                </span>
              </div>
            )}
            <div className="flex justify-between border-t border-ink-200 dark:border-ink-600 pt-1.5 mt-1.5">
              <span className="font-medium">Balance</span>
              <span
                className={`font-mono font-bold ${balance > 0 ? "text-red-600" : "text-green-600"}`}
              >
                {formatRWF(balance)}
              </span>
            </div>
          </div>

          {/* Waive confirmation */}
          {confirming && (
            <div className="bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800 rounded-lg p-3 space-y-2">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-orange-500 shrink-0 mt-0.5" />
                <p className="text-sm text-orange-700 dark:text-orange-400">
                  This will mark the invoice as <strong>waived</strong> and no
                  payment will be required. This action cannot be undone.
                </p>
              </div>
              <div className="flex gap-2 justify-end">
                <button
                  className="btn-ghost btn-xs"
                  onClick={() => setConfirming(false)}
                >
                  Cancel
                </button>
                <button
                  className="btn-xs bg-orange-500 hover:bg-orange-600 text-white rounded px-3"
                  onClick={() => waiveMutation.mutate()}
                  disabled={waiveMutation.isPending}
                >
                  {waiveMutation.isPending && (
                    <Loader2 className="w-3 h-3 animate-spin" />
                  )}
                  Confirm Waive
                </button>
              </div>
            </div>
          )}

          <div className="flex gap-2 justify-between pt-1">
            <div>
              {canWaive && !confirming && (
                <button
                  className="btn-ghost btn-sm text-orange-600 dark:text-orange-400"
                  onClick={() => setConfirming(true)}
                >
                  <AlertTriangle className="w-3.5 h-3.5" /> Waive
                </button>
              )}
            </div>
            <div className="flex gap-2">
              <button className="btn-ghost btn-sm" onClick={onClose}>
                Close
              </button>
              {canPay && (
                <button
                  className="btn-primary btn-sm flex flex-row items-center gap-2"
                  onClick={onPay}
                >
                  <div>
                    <Banknote className="w-3.5 h-3.5" />
                  </div>{" "}
                  <div className="truncate">Record Payment</div>
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
    </ModalPortal>
  );
}

// ─── Manual Invoice Modal ─────────────────────────────────────────────────────

type StructureAnalysis = {
  structure: FeeStructure;
  plan: "full_year" | "per_semester" | "per_installment";
  invoicedTotal: number;
  remaining: number;
  isFullyInvoiced: boolean;
  /** pre-filled amount for this invoice */
  suggested: number;
  invoicedSemesters: (1 | 2)[];
  // per_semester
  perSem?: number;
  // per_installment
  perInstall?: number;
  installmentCount?: number;
  existingCount?: number;
  nextInstall?: number;
};

function analyseStructure(
  s: FeeStructure,
  existingInvoices: FeeInvoice[],
): StructureAnalysis {
  const existing = existingInvoices.filter(
    (inv) => inv.fee_structure_id === s.id,
  );
  const invoicedTotal = existing.reduce(
    (sum, inv) => sum + Number(inv.amount_due),
    0,
  );
  const invoicedSemesters = existing
    .map((inv) => inv.semester)
    .filter((x): x is 1 | 2 => x === 1 || x === 2);
  const plan = s.payment_plan ?? "full_year";
  const remaining = Math.max(0, s.amount - invoicedTotal);

  if (plan === "per_semester") {
    const perSem = s.amount / 2;
    return {
      structure: s,
      plan,
      invoicedTotal,
      remaining,
      isFullyInvoiced: invoicedSemesters.length >= 2,
      suggested: perSem,
      invoicedSemesters,
      perSem,
    };
  }
  if (plan === "per_installment") {
    const installmentCount = Math.max(1, s.installment_count ?? 1);
    const perInstall = s.amount / installmentCount;
    return {
      structure: s,
      plan,
      invoicedTotal,
      remaining,
      isFullyInvoiced: existing.length >= installmentCount,
      suggested: perInstall,
      invoicedSemesters,
      perInstall,
      installmentCount,
      existingCount: existing.length,
      nextInstall: existing.length + 1,
    };
  }
  // full_year
  return {
    structure: s,
    plan: "full_year",
    invoicedTotal,
    remaining,
    isFullyInvoiced: remaining <= 0,
    suggested: remaining,
    invoicedSemesters,
  };
}

function ManualInvoiceModal({
  studentId,
  yearId,
  existingInvoices,
  onClose,
  onDone,
}: {
  studentId: string;
  yearId: number;
  existingInvoices: FeeInvoice[];
  onClose: () => void;
  onDone: () => void;
}) {
  const [mode, setMode] = useState<"structure" | "custom">("structure");

  // ── Structure mode ────────────────────────────────────────────────────────
  const [structId, setStructId] = useState<number | "">("");
  const [structSem, setStructSem] = useState<1 | 2 | "">("");
  const [structDesc, setStructDesc] = useState("");
  const [structAmount, setStructAmount] = useState(0);
  const [structDue, setStructDue] = useState("");

  // ── Custom mode ───────────────────────────────────────────────────────────
  const [custType, setCustType] = useState<FeeType>("FINE");
  const [custSem, setCustSem] = useState<"" | "1" | "2">("");
  const [custDesc, setCustDesc] = useState("");
  const [custAmount, setCustAmount] = useState(0);
  const [custDue, setCustDue] = useState("");

  // ── Fee structures ────────────────────────────────────────────────────────
  const structuresQ = useQuery({
    queryKey: ["finance", "structures", yearId],
    queryFn: () =>
      feeStructureService.list({ academic_year_id: yearId, is_active: 1 }),
    enabled: mode === "structure",
  });
  const structures = (structuresQ.data?.data ?? []) as FeeStructure[];

  // ── Analysis of selected structure ───────────────────────────────────────
  const analysis = useMemo<StructureAnalysis | null>(() => {
    if (!structId) return null;
    const s = structures.find((x) => x.id === structId);
    return s ? analyseStructure(s, existingInvoices) : null;
  }, [structId, structures, existingInvoices]);

  // Auto-fill description/amount/semester when structure changes
  useEffect(() => {
    if (!analysis) return;
    setStructDesc(analysis.structure.label);
    setStructAmount(analysis.suggested);
    if (analysis.plan === "per_semester") {
      const available = ([1, 2] as const).filter(
        (s) => !analysis.invoicedSemesters.includes(s),
      );
      setStructSem(available[0] ?? "");
    } else {
      setStructSem("");
    }
  }, [analysis?.structure.id]);

  // ── Mutations ─────────────────────────────────────────────────────────────
  const structMutation = useMutation({
    mutationFn: () => {
      if (!structId || !analysis) throw new Error("Select a fee structure");
      return ledgerService.createInvoice({
        student_id: studentId,
        academic_year_id: yearId,
        fee_structure_id: structId as number,
        fee_type: analysis.structure.fee_type,
        description: structDesc,
        amount_due: structAmount,
        due_date: structDue || null,
        semester:
          analysis.plan === "per_semester" && structSem
            ? (structSem as 1 | 2)
            : null,
      });
    },
    onSuccess: () => {
      toast.success("Invoice created");
      onDone();
    },
    onError: (e: any) =>
      toast.error(e?.response?.data?.message ?? "Failed to create invoice"),
  });

  const custMutation = useMutation({
    mutationFn: () =>
      ledgerService.createInvoice({
        student_id: studentId,
        academic_year_id: yearId,
        fee_type: custType,
        description: custDesc,
        amount_due: custAmount,
        due_date: custDue || null,
        semester: custSem ? (Number(custSem) as 1 | 2) : null,
      }),
    onSuccess: () => {
      toast.success("Invoice created");
      onDone();
    },
    onError: (e: any) =>
      toast.error(e?.response?.data?.message ?? "Failed to create invoice"),
  });

  const isPending = structMutation.isPending || custMutation.isPending;

  // ── Structure dropdown options ────────────────────────────────────────────
  const structOptions = useMemo(
    () =>
      structures.map((s) => {
        const a = analyseStructure(s, existingInvoices);
        const planLabel =
          s.payment_plan === "per_semester"
            ? "Per Sem"
            : s.payment_plan === "per_installment"
              ? `${s.installment_count ?? "?"} Installments`
              : "Full Year";
        return {
          value: s.id,
          label: `${s.label} (${planLabel}) — ${formatRWF(s.amount)}${a.isFullyInvoiced ? " ✓" : ""}`,
        };
      }),
    [structures, existingInvoices],
  );

  const custTypeOptions = MANUAL_FEE_TYPES.map((t) => ({
    value: t,
    label: FEE_TYPE_LABELS[t],
  }));

  const structCanSubmit =
    !!structId &&
    !!analysis &&
    !analysis.isFullyInvoiced &&
    !!structDesc &&
    structAmount > 0 &&
    (analysis.plan !== "per_semester" || !!structSem);

  return (
    <ModalPortal>
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50">
      <div className="flex min-h-full items-center justify-center p-4">
        <div className="bg-white dark:bg-ink-800 rounded-xl shadow-xl w-full max-w-md p-6 space-y-4">
          {/* Header */}
          <div className="flex items-center justify-between">
            <h3 className="text-base font-semibold">New Invoice</h3>
            <button className="btn-ghost btn-xs" onClick={onClose}>
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Mode tabs */}
          <div className="flex rounded-lg overflow-hidden border border-ink-200 dark:border-ink-600 text-sm">
            {(["structure", "custom"] as const).map((m) => (
              <button
                key={m}
                className={`flex-1 py-1.5 font-medium transition-colors ${
                  mode === m
                    ? "bg-brand text-white"
                    : "text-ink-500 hover:bg-ink-50 dark:hover:bg-ink-700/50"
                }`}
                onClick={() => setMode(m)}
              >
                {m === "structure" ? "From Fee Structure" : "Custom Fee"}
              </button>
            ))}
          </div>

          {/* ── FROM FEE STRUCTURE ── */}
          {mode === "structure" && (
            <div className="space-y-3 text-sm">
              {structuresQ.isLoading ? (
                <div className="flex justify-center py-6">
                  <Loader2 className="w-5 h-5 animate-spin text-brand" />
                </div>
              ) : structures.length === 0 ? (
                <p className="text-center text-ink-400 py-4 text-xs">
                  No active fee structures found for this academic year.
                </p>
              ) : (
                <>
                  <div>
                    <label className="block text-xs text-ink-500 mb-1">
                      Fee Structure *
                    </label>
                    <SearchableSelect
                      options={structOptions}
                      value={structId}
                      onChange={(v) => setStructId(v as number)}
                      placeholder="Select fee structure…"
                    />
                  </div>

                  {analysis && (
                    <>
                      {/* Analysis panel */}
                      <div className="rounded-lg border border-ink-100 dark:border-ink-700 overflow-hidden text-xs">
                        <div className="bg-ink-50 dark:bg-ink-700/40 px-3 py-2 flex items-center justify-between">
                          <span className="font-medium text-ink-700 dark:text-ink-200">
                            Fee Structure Analysis
                          </span>
                          <span
                            className={`px-2 py-0.5 rounded-full font-semibold ${
                              analysis.plan === "full_year"
                                ? "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300"
                                : analysis.plan === "per_semester"
                                  ? "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300"
                                  : "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300"
                            }`}
                          >
                            {analysis.plan === "full_year"
                              ? "Full Year"
                              : analysis.plan === "per_semester"
                                ? "Per Semester"
                                : `Per Installment (${analysis.installmentCount})`}
                          </span>
                        </div>
                        <div className="divide-y divide-ink-100 dark:divide-ink-700">
                          <div className="px-3 py-2 flex justify-between">
                            <span className="text-ink-500">Total amount</span>
                            <span className="font-mono font-semibold">
                              {formatRWF(analysis.structure.amount)}
                            </span>
                          </div>
                          <div className="px-3 py-2 flex justify-between">
                            <span className="text-ink-500">
                              Already invoiced
                            </span>
                            <span className="font-mono text-green-600">
                              {formatRWF(analysis.invoicedTotal)}
                            </span>
                          </div>
                          {analysis.plan === "per_installment" && (
                            <div className="px-3 py-2 flex justify-between">
                              <span className="text-ink-500">
                                Installments done
                              </span>
                              <span className="font-mono">
                                {analysis.existingCount} /{" "}
                                {analysis.installmentCount}
                              </span>
                            </div>
                          )}
                          {analysis.plan === "per_semester" && (
                            <div className="px-3 py-2 flex justify-between">
                              <span className="text-ink-500">
                                Semesters invoiced
                              </span>
                              <span className="font-mono">
                                {analysis.invoicedSemesters.length > 0
                                  ? analysis.invoicedSemesters
                                      .map((s) => `S${s}`)
                                      .join(", ")
                                  : "None yet"}
                              </span>
                            </div>
                          )}
                          <div className="px-3 py-2 flex justify-between font-medium">
                            <span>Remaining balance</span>
                            <span
                              className={`font-mono font-bold ${
                                analysis.remaining > 0
                                  ? "text-red-600"
                                  : "text-green-600"
                              }`}
                            >
                              {formatRWF(analysis.remaining)}
                            </span>
                          </div>
                        </div>
                      </div>

                      {analysis.isFullyInvoiced ? (
                        <div className="flex items-center gap-2 text-green-700 dark:text-green-400 bg-green-50 dark:bg-green-900/20 rounded-lg px-3 py-2 text-xs font-medium">
                          <CheckCircle2 className="w-4 h-4 shrink-0" />
                          All invoices have been created for this fee structure.
                        </div>
                      ) : (
                        <>
                          {/* Per-semester selector */}
                          {analysis.plan === "per_semester" && (
                            <div>
                              <label className="block text-xs text-ink-500 mb-1">
                                Semester *
                              </label>
                              <div className="flex gap-2">
                                {([1, 2] as const).map((s) => {
                                  const done =
                                    analysis.invoicedSemesters.includes(s);
                                  return (
                                    <button
                                      key={s}
                                      disabled={done}
                                      onClick={() => setStructSem(s)}
                                      className={`flex-1 py-2 rounded-lg border text-xs font-medium transition-colors ${
                                        done
                                          ? "border-ink-200 dark:border-ink-700 text-ink-300 dark:text-ink-600 cursor-not-allowed bg-ink-50 dark:bg-ink-800"
                                          : structSem === s
                                            ? "border-brand bg-brand/10 text-brand dark:bg-brand/20"
                                            : "border-ink-200 dark:border-ink-600 hover:border-brand/60 hover:bg-brand/5"
                                      }`}
                                    >
                                      Semester {s}
                                      {done && (
                                        <span className="ml-1 text-green-500">
                                          ✓
                                        </span>
                                      )}
                                    </button>
                                  );
                                })}
                              </div>
                            </div>
                          )}

                          {/* Per-installment info */}
                          {analysis.plan === "per_installment" && (
                            <div className="flex items-start gap-2 bg-blue-50 dark:bg-blue-900/20 rounded-lg px-3 py-2 text-xs text-blue-700 dark:text-blue-300">
                              <Info className="w-3.5 h-3.5 mt-0.5 shrink-0" />
                              <span>
                                This will create installment{" "}
                                <strong>{analysis.nextInstall}</strong> of{" "}
                                <strong>{analysis.installmentCount}</strong>.
                                Suggested amount:{" "}
                                <strong>
                                  {formatRWF(analysis.perInstall ?? 0)}
                                </strong>
                              </span>
                            </div>
                          )}

                          <div>
                            <label className="block text-xs text-ink-500 mb-1">
                              Description *
                            </label>
                            <input
                              className="input input-sm w-full"
                              value={structDesc}
                              onChange={(e) => setStructDesc(e.target.value)}
                            />
                          </div>

                          <div>
                            <label className="block text-xs text-ink-500 mb-1">
                              Amount (RWF) *
                            </label>
                            <input
                              type="number"
                              min={1}
                              className="input input-sm w-full"
                              value={structAmount}
                              onChange={(e) =>
                                setStructAmount(Number(e.target.value))
                              }
                            />
                            {analysis.plan !== "full_year" && (
                              <p className="text-[10px] text-ink-400 mt-0.5">
                                Suggested: {formatRWF(analysis.suggested)}
                              </p>
                            )}
                          </div>

                          <div>
                            <label className="block text-xs text-ink-500 mb-1">
                              Due Date (optional)
                            </label>
                            <input
                              type="date"
                              className="input input-sm w-full"
                              value={structDue}
                              onChange={(e) => setStructDue(e.target.value)}
                            />
                          </div>
                        </>
                      )}
                    </>
                  )}
                </>
              )}
            </div>
          )}

          {/* ── CUSTOM FEE ── */}
          {mode === "custom" && (
            <div className="space-y-3 text-sm">
              <div>
                <label className="block text-xs text-ink-500 mb-1">
                  Fee Type *
                </label>
                <SearchableSelect
                  options={custTypeOptions}
                  value={custType}
                  onChange={(v) => setCustType(v as FeeType)}
                  placeholder="Select fee type…"
                />
              </div>

              <div>
                <label className="block text-xs text-ink-500 mb-1">
                  Semester (optional)
                </label>
                <select
                  className="input input-sm w-full"
                  value={custSem}
                  onChange={(e) => setCustSem(e.target.value as "" | "1" | "2")}
                >
                  <option value="">— Not semester-specific —</option>
                  <option value="1">Semester 1</option>
                  <option value="2">Semester 2</option>
                </select>
              </div>

              <div>
                <label className="block text-xs text-ink-500 mb-1">
                  Description *
                </label>
                <input
                  className="input input-sm w-full"
                  value={custDesc}
                  onChange={(e) => setCustDesc(e.target.value)}
                  placeholder="e.g. Library fine – overdue books"
                />
              </div>

              <div>
                <label className="block text-xs text-ink-500 mb-1">
                  Amount (RWF) *
                </label>
                <input
                  type="number"
                  min={1}
                  className="input input-sm w-full"
                  value={custAmount}
                  onChange={(e) => setCustAmount(Number(e.target.value))}
                />
              </div>

              <div>
                <label className="block text-xs text-ink-500 mb-1">
                  Due Date (optional)
                </label>
                <input
                  type="date"
                  className="input input-sm w-full"
                  value={custDue}
                  onChange={(e) => setCustDue(e.target.value)}
                />
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="flex gap-2 justify-end pt-1 border-t border-ink-100 dark:border-ink-700">
            <button className="btn-ghost btn-sm" onClick={onClose}>
              Cancel
            </button>
            {mode === "structure" ? (
              <button
                className="btn-primary btn-sm"
                disabled={isPending || !structCanSubmit}
                onClick={() => structMutation.mutate()}
              >
                {isPending && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
                Create Invoice
              </button>
            ) : (
              <button
                className="btn-primary btn-sm"
                disabled={isPending || !custDesc || custAmount <= 0}
                onClick={() => custMutation.mutate()}
              >
                {isPending && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
                Create Invoice
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
    </ModalPortal>
  );
}

// ─── Helper sub-components ────────────────────────────────────────────────────

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex justify-between gap-4">
      <span className="text-ink-500 shrink-0">{label}</span>
      <span className="text-right font-medium text-ink-800 dark:text-ink-100">
        {value}
      </span>
    </div>
  );
}

function SummaryCard({
  label,
  value,
  color,
}: {
  label: string;
  value: number | null;
  color: string;
}) {
  return (
    <div className="card p-4">
      <p className="text-xs text-ink-500 mb-1">{label}</p>
      <p className={`text-xl font-bold ${color}`}>{formatRWF(value ?? 0)}</p>
    </div>
  );
}
